version: "3.7"

services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql-forum-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
    ports:
      - "3307:3306"

volumes:
  mysql-forum-data:
