version: "3.7"

services:
  mysql:
    image: mysql:8.0.30
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
    ports:
      - "3307:3306"

volumes:
  mysql-data:
